kind: Namespace
apiVersion: v1
metadata:
  name: onlineboutique
  annotations:
    configsync.gke.io/cluster-name-selector: staging
    cnrm.cloud.google.com/project-id : mabenoit-demo
  labels:
    istio.io/rev: asm-191-1
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
spec:
  {}