apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      serviceAccountName: default
      containers:
      - name: whereami
        image: rseroter/core-hello-kubernetes
        ports:
          - name: http
            containerPort: 8080